### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by HuJiaoHJ** [HuJiaoHJ/blog#8]

**Comment by HuJiaoHJ** [comment]
### webpack production 打包问题排查及解决

将项目依赖的npm包版本固化之后，webpack production 打包就出现如下问题：

```bash
errors xxx.js from uglifyjs 
undefined
```

可以发现，详细的错误信息为undefined，这个时候需要配置 [uglifyjs-webpack-plugin](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#parallel) 插件的 parallel 选项为false，即可显示详细错误信息，配置如下：

```JavaScript
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

module.exports = {
  //...
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
           parallel: false
      })
    ]
  }
}
```

配置之后，重新打包，错误信息如下：

```bash
errors xxx.js from uglifyjs 
TypeError: sym.definition is not a function
```

解决此问题：https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn ，需在 package.json 中添加如下配置：

```JavaScript
"resolutions": {
    "uglify-es": "npm:terser"
}
```

重新安装依赖、打包，问题就解决了

当然，webpack打包问题肯定不都是这个问题，这个tip重点是通过配置将详细的错误信息展示出来，方便问题排查

**Comment by HuJiaoHJ** [comment]
### webpack tree-shaking 不生效

#### 原因

babel会把 ES6 Module 转换成 commonjs 模块（参考：https://babeljs.io/docs/en/babel-preset-env#modules ）

而webpack本身是依赖 ES6 Module 语法来做 tree-shaking（参考：https://webpack.js.org/guides/tree-shaking/#src/components/Sidebar/Sidebar.jsx）

所以babel默认的配置会导致webpack tree-shaking失效

#### 解决

将 babel preset 配置修改如下：

```JavaScript
{
  presets: [
    [
      '@babel/preset-env', 
      {
        'modules': false,
      }
    ]
  ],
}
```

**Comment by HuJiaoHJ** [comment]
### css modules 动画（Animation）编译问题

```CSS
@keyframes marquee {
    from {
        transform: translateX(0);
    }
    to {
        transform: translateX(-430px);
    }
}

.marquee {
    animation: 2s marquee linear infinite;
}
```

使用以上代码，用户不生效，原因是时间写在动画名称之前不识别，需要做如下调整：

```CSS
.marquee {
    animation: marquee 2s linear infinite;
}
```

#### 怎么声明全局@keyframes

```
@keyframes :global(marquee) {
    from {
        transform: translateX(0);
    }
    to {
        transform: translateX(-430px);
    }
}
```
